apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-files
          emptyDir: {}
      containers:
        - name: writer
          image: tvaanane02/log-output-writer:1.10
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files
        - name: reader
          image: tvaanane02/log-output-reader:1.10
          env:
            - name: PORT
              value: "8000"
          volumeMounts:
            - name: shared-files
              mountPath: /usr/src/app/files